# Generated by Django 4.2.2 on 2023-09-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=32, unique=True)),
                ("price", models.FloatField(default=1)),
                ("type", models.CharField(default="", max_length=32)),
                ("brand", models.CharField(default="", max_length=32)),
            ],
        ),
    ]
