# Generated by Django 4.2.2 on 2023-09-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(default="", max_length=32),
        ),
    ]
